baseURL: https://artfulbytes.com/

security:
  funcs:
    getenv:
      - '^HUGO_'
      - '^CI$'
      - '^CONVERTKIT_API_SECRET$'
languageCode: en-us
title: Artful Bytes
theme: ["PaperMod"]

params:
  defaultTheme: dark
  assets:
    css:
      - css/custom.css
  footer:
    hideCopyright: true
