[build]
  command = "hugo"
  publish = "public"

[context.production.environment]
  HUGO_VERSION = "0.131.0"

[[redirects]]
  from = "/bots2d-blogpost"
  to = "https://github.com/artfulbytes/website/tree/main/content/blog/bots2d-simulator"
  status = 301

[[redirects]]
  from = "/mcu-i2c-driver"
  to = "https://github.com/artfulbytes/website/tree/main/content/blog/i2c-driver-mcu"
  status = 301

[[redirects]]
  from = "/vl53l0x-post"
  to = "https://github.com/artfulbytes/website/tree/main/content/blog/vl53l0x-post"
  status = 301

[[redirects]]
  from = "/makefile-microcontroller"
  to = "https://github.com/artfulbytes/website/tree/main/content/blog/makefile-microcontroller"
  status = 301
